version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  db:
    build: db
    restart: always
    env_file: 
      - db/db.env
    ports:
      - "6543:5432"
    volumes:
      - nfl-data:/var/lib/postgresql/data/

volumes:
  nfl-data:
