# Generated by Django 3.1.4 on 2021-01-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='jersey_number',
            new_name='jerseyNumber',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='college_name',
            new_name='playerCollege',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='height',
            new_name='playerHeight',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='id',
            new_name='playerID',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nfl_id',
            new_name='playerNFLID',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='display_name',
            new_name='playerName',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='playerPosition',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='playerTeam',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='weight',
            new_name='playerWeight',
        ),
    ]
