# Generated by Django 3.1.5 on 2021-01-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='playerCollege',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='playerPosition',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='playerTeam',
            new_name='team_name',
        ),
    ]
