# Generated by Django 3.1.4 on 2021-01-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210106_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='birth_date',
            new_name='birthDate',
        ),
    ]
